Check that mr is installed before using it

diff --git a/movein b/movein
--- a/movein
+++ b/movein
@@ -96,6 +96,11 @@ init() {
 	exit 1
     fi
 
+    if ! which mr > /dev/null; then
+        echo '"mr" not found in the PATH'
+        exit 1
+    fi
+
     echo -n "git server hostname? [git.vireo.org] " 
     read GIT_HOST
     if [ -z "$GIT_HOST" ]; then 
